name: build and push docker
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - name: Taking files
        uses: actions/checkout@v3
      - name: Login Docker account
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER.NAME }}"
          password: "${{ secrets.DOCKER.PASSWORD }}"

      - name: Build and push
        run: |
          docker image build -t pratishtharya/maven_pipeline:latest .
          docker push pratishtharya/maven_pipeline:latest