name: build and push docker
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3
      - name: Testing package
        run: mvn clean package

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Taking files
        uses: actions/checkout@v3
      - name: Login Docker account
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_NAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Creating short SHA
        id: sha-id
        run: echo "{sha4}"="{$(echo ${GITHUB_SHA} | cut -c1-4)}" >> GITHUB_OUTPUT  

      - name: Build and push
        run: |
          docker image build -t pratishthaarya/mavenproject:${{ steps.sha-id.outputs.sha4 }} .
          docker push pratishthaarya/mavenproject:${{ steps.sha-id.outputs.sha4 }}